### ISSUE TITLE
ASP.NET Core

### ISSUE THREAD

**Issue by pauldbentley** [ardalis/AggregateEvents#1]
Hi Steve,

Is this safe to use with ASP.NET Core?  I read about issues with `ThreadStatic` and to use `AsyncLocal<T>` instead.  Do you have any experience of this?

Thanks

**Comment by ardalis** [comment]
I haven't run this particular sample's code style in a production app, and I'm not sure what you're referring to regarding ThreadStatic issues, so I guess my answer is "I don't know" ?

**Comment by pauldbentley** [comment]
It seems to behave very strangely with ASP.NET Core.  I've just tried and sometimes it works fine.  If I refresh my page to keep calling task.MarkComplete() sometimes _actions grows to have multiple handlers registered, sometimes it's empty and the handler in Project doesn't fire.  I don't think I understand threading enough to use this pattern which is a shame as its very clean.

**Comment by ardalis** [comment]
Did you try having it use `AsyncLocal<T>`? I haven't worked with that and your issue here was the first I've heard of it, so if you have any experience to share I'd appreciate it.

It's probably also worth updating this sample to use something else to do the message orchestration. For example, MediatR. That way we're not trying to figure out the threading and other issues, since that library's already well-proven.

**Comment by pauldbentley** [comment]
Yes I think MediatR might be a better option, plus I've tried a version which uses ObservableCollection and regular events/handlers https://github.com/pauldbentley/AggregateEvents

**Comment by jlwalkerlg** [comment]
@ardalis I was curious about this too. From what I've read, the issue is that the `ThreadStatic` attribute makes a static variable unique to each _thread_, but not to each _web request_, because each request can jump between different threads during its lifetime.

So the `AggregateEvents.AggregateEvents._actions` variable maybe isn't reliable for registering and dispatching domain events? Seems like the only reliable way to make sure static variables are unique to each request is by using `Microsoft.AspNetCore.Http.HttpContext.Items`.

- https://stackoverflow.com/questions/4791208/threadstaticattribute-in-asp-net
- https://github.com/dotnet/aspnetcore/issues/1371

**Comment by ardalis** [comment]
Thanks. I’ll investigate. Might be that a scoped service managed by DI could work.
